// GENERATED by marin/scripts/gen-identities-ts from identities.yaml — do not edit.
// Display-only enrichment (short name + GitHub avatar handle) keyed by
// canonical user id. Attribution (teams, bytes) still comes from meta/rules.
export interface IdentityRec {
  name: string
  github?: string
  team?: string
}

export const IDENTITIES: Record<string, IdentityRec> = {
  "ahmed-ahmed": {
    "github": "ahmeda14960",
    "name": "Ahmed",
    "team": "stanford"
  },
  "alex-merose": {
    "github": "alxmrs",
    "name": "Alex",
    "team": "oa"
  },
  "calvin-xu": {
    "github": "Calvin-Xu",
    "name": "Calvin",
    "team": "stanford"
  },
  "chi-heem-wong": {
    "github": "chiheem",
    "name": "Chi-Heem",
    "team": "stanford"
  },
  "christopher-chou": {
    "github": "BabyChouSr",
    "name": "Christopher",
    "team": "stanford"
  },
  "david-hall": {
    "github": "dlwh",
    "name": "David",
    "team": "oa"
  },
  "elyas-obbad": {
    "github": "eobbad",
    "name": "Elyas",
    "team": "stanford"
  },
  "eric-czech": {
    "github": "eczech",
    "name": "Eric",
    "team": "oa"
  },
  "exedev": {
    "name": "Exedev",
    "team": "oa"
  },
  "herumb-shandilya": {
    "github": "krypticmouse",
    "name": "Herumb",
    "team": "stanford"
  },
  "jason-wang": {
    "github": "blahBlahhhJ",
    "name": "Jason",
    "team": "stanford"
  },
  "julian": {
    "name": "Julian",
    "team": "stanford"
  },
  "kaiyue-wen": {
    "github": "WhenWen",
    "name": "Kaiyue",
    "team": "stanford"
  },
  "kevin-li": {
    "github": "AlienKevin",
    "name": "Kevin",
    "team": "stanford"
  },
  "larry-dial": {
    "github": "ClassicLarry",
    "name": "Larry",
    "team": "oa"
  },
  "matt-wittmann": {
    "github": "mcwitt",
    "name": "Matt",
    "team": "oa"
  },
  "michael-ryan": {
    "name": "Michael",
    "team": "stanford"
  },
  "moojin-kim": {
    "github": "moojink",
    "name": "Moojin",
    "team": "stanford"
  },
  "nikil-ravi": {
    "github": "nikil-ravi",
    "name": "Nikil",
    "team": "stanford"
  },
  "percy-liang": {
    "github": "percyliang",
    "name": "Percy",
    "team": "stanford"
  },
  "pranshu-chaturvedi": {
    "github": "pc0618",
    "name": "Pranshu",
    "team": "stanford"
  },
  "rafal-wojdyla": {
    "github": "ravwojdyla",
    "name": "Rafal",
    "team": "oa"
  },
  "rohith-kuditipudi": {
    "github": "RohithKuditipudi",
    "name": "Rohith",
    "team": "stanford"
  },
  "romain-yon": {
    "github": "yonromai",
    "name": "Romain",
    "team": "oa"
  },
  "runner": {
    "name": "Runner",
    "team": "oa"
  },
  "russell-power": {
    "github": "rjpower",
    "name": "Russell",
    "team": "oa"
  },
  "ryan-williams": {
    "github": "ryan-williams",
    "name": "Ryan",
    "team": "oa"
  },
  "suhas-kotha": {
    "github": "kothasuhas",
    "name": "Suhas",
    "team": "stanford"
  },
  "will-held": {
    "github": "Helw150",
    "name": "Will",
    "team": "oa"
  },
  "yael-elmatad": {
    "github": "yaelelmatad",
    "name": "Yael",
    "team": "oa"
  },
  "ziqing-huang": {
    "github": "ziqing-huang",
    "name": "Ziqing",
    "team": "stanford"
  }
}
