// Object stores the dashboard can render. Each one publishes the same layer-3
// trio (`<base>/scans.json`, `<base>/<scan>/{tree,age,meta}.json`) and lives at
// its own URL path, so adding a store is a row here plus data in the bucket.
//
// Data comes from the snapshot bucket via `functions/data/[[path]].ts`, not
// from the site build: GCS snapshots sit at `snapshots/<date>/`, and every
// other store gets a named subdir (`snapshots/cw/<date>/`). The Function's
// date-dir filter keeps a store subdir out of the GCS scan list, and its
// generic `/data/<rel>` -> `snapshots/<rel>` mapping serves the payloads
// unchanged -- only the `scans.json` listing needed a store prefix.
//
// Baking the JSONs into `public/` was the other option; it was rejected because
// publishing a scan would then require a site redeploy, which is exactly the
// staleness the data Function was introduced to fix.
export interface Store {
  key: string
  label: string    // store selector button
  title: string    // <h1>, <title>, unfurl title
  desc: string     // meta description / unfurl description
  path: string     // app route
  scheme: string   // URI scheme for treemap paths/tooltips
  base: string     // layer-3 data root
  ogImage: string  // unfurl card, generated by `pnpm shots` from `<path>/og`
  prices: boolean  // GCS storage-class list pricing applies to this store
}

export const STORES: Store[] = [
  {
    key: 'gcs',
    label: 'GCS',
    title: 'Marin GCS usage',
    desc: 'Per-group storage attribution across the six marin-* GCS buckets.',
    path: '/',
    scheme: 'gs://',
    base: '/data',
    ogImage: '/og.jpg',
    prices: true,
  },
  {
    key: 'cw',
    label: 'CoreWeave',
    title: 'Marin CoreWeave usage',
    desc: 'Storage usage across the marin-us-east-02a CoreWeave S3 bucket.',
    path: '/cw',
    scheme: 's3://',
    base: '/data/cw',
    ogImage: '/og-cw.jpg',
    prices: false,
  },
]

export const DEFAULT_STORE = STORES[0]

// Longest matching path wins, so `/cw` beats the `/` default.
export const storeForPath = (pathname: string): Store =>
  [...STORES]
    .sort((a, b) => b.path.length - a.path.length)
    .find(s => s.path !== '/' && (pathname === s.path || pathname.startsWith(`${s.path}/`)))
  ?? DEFAULT_STORE
