secretsprovider: gcpkms://projects/oa-internal-450019/locations/global/keyRings/ops/cryptoKeys/pulumi
encryptedkey: CiQAqKOWSFg1RxWOw+z3IycCWkyuUHqOGpbXRTZW2NwWU51WJLMSSAAw+4V0Y7dVUeF5Wm4G0d42EjChzjw3kRDye61UR5KYj8wJjfcvtkcER/QnOsm2h5ikGeqJfi1XtIypjVDbR37xh/dhen5gTw==
config:
  gcs-usage-cf:accountId: 74981a43be0de7712369306c7b19133d
  gcs-usage-cf:zoneId: 169959d6aafcbfd77764b8efafa3a509   # oa.dev
  gcs-usage-cf:pagesProject: oa-gcs-usage
  gcs-usage-cf:domain: gcs.oa.dev
  gcs-usage-cf:d1Name: oa-gcs-usage-auth
  gcs-usage-cf:branchAliases:
    - {domain: dev.gcs.oa.dev, branch: dev}
  gcs-usage-cf:kvName: oa-gcs-usage-cache
  gcs-usage-cf:r2Bucket: oa-gcs-usage-index   # Worker-served indexes (static name search)
